name: 课程提醒  # 工作流名称，用于课程提醒推送

on:
  schedule:  # 定时触发器
    - cron: '45 23 * * *'  # 7:45 北京时间
    - cron: '45 1 * * *'   # 9:45 北京时间  
    - cron: '45 4 * * *'   # 12:45 北京时间
    - cron: '45 6 * * *'   # 14:45 北京时间
    - cron: '40 8 * * *'   # 16:40 北京时间
    - cron: '55 10 * * *'  # 18:55 北京时间
  workflow_dispatch:  # 手动触发器

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: 课程提醒推送

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.workspace }}/.github/requirements.txt

    - name: Run course reminder
      run: |
        python ${{ github.workspace }}/.github/kebiao.py

    env:
      APP_ID: ${{ secrets.APP_ID }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
      USER_IDS: ${{ secrets.USER_IDS }}
      NAME: ${{ secrets.NAME }}
